%% 5B3D-Finger-Model: Main
%% Author: Alexander B. Ambrose
%% Date: 8-6-2025

%% Description:
% The getJacobians function return the jacobian for the following points:
%   p_1 -> the contact point on the proximal link of the finger
%   p_2 -> the contact point on the distal link of the finger
%   p_c -> the point here the compression spring is truncated

%% This function takes in the following inputs:
%   param -> the structure of parameters to update
%   t_1_ -> angle \theta_1 (scalar)
%   t_2_ -> angle \theta_2 (scalar)
%   t_3_ -> angle \theta_3 (scalar)

function Jac = getJacobians(param, t_1_, t_2_, t_3_)
    if numel(t_1_) == 1 && numel(t_1_) == numel(t_2_) && numel(t_1_) == numel(t_3_)
        %% All of the angles are scalars
        J1 = ...
            [-param.p1.*sin(t_1_) - ...
                    param.t*cos(t_1_), 0; ...
              param.p1.*cos(t_1_) - ...
                    param.t*sin(t_1_), 0];
    
        J2 = ...
            [-param.a.*sin(t_1_) - ...
                param.p2.*sin(t_1_ + ...
                t_2_) - param.t.*cos(t_1_ + ...
                t_2_), ...
            -param.p2.*sin(t_1_ + ...
                t_2_) - param.t.*cos(t_1_ + ...
                t_2_); ...
            param.a.*cos(t_1_) + param.p2.*cos(...
                t_1_ + t_2_) - ...
                param.t.*sin(t_1_ + t_2_), ...
            param.p2.*cos(t_1_ + ...
                t_2_) - param.t.*sin(t_1_ + ...
                t_2_)];
    
    
        beta = t_1_ + t_2_ - param.alpha;
        JC = ...
            [-param.a.*sin(t_1_) - param.b.*sin(beta), ...
            -param.b.*sin(beta); ...
            param.a*cos(t_1_) + param.b.*cos(beta), ...
            param.b.*cos(beta)];
    elseif numel(t_1_) > 1 && numel(t_1_) == numel(t_2_) && numel(t_1_) == numel(t_3_)
        %% angles are vectors with the same length
        for ii = 1:numel(t_1_)
            J1(:, :, ii) = ...
                [-param.p1(ii).*sin(t_1_(ii)) - ...
                        param.t*cos(t_1_(ii)), 0; ...
                  param.p1(ii).*cos(t_1_(ii)) - ...
                        param.t*sin(t_1_(ii)), 0];
        
            J2(:, :, ii) = ...
                [-param.a.*sin(t_1_(ii)) - ...
                    param.p2(ii).*sin(t_1_(ii) + ...
                    t_2_(ii)) - param.t.*cos(t_1_(ii) + ...
                    t_2_(ii)), ...
                -param.p2(ii).*sin(t_1_(ii)+ ...
                    t_2_(ii)) - param.t.*cos(t_1_(ii) + ...
                    t_2_(ii)); ...
                param.a.*cos(t_1_(ii)) + param.p2(ii).*cos(...
                    t_1_(ii) + t_2_(ii)) - ...
                    param.t.*sin(t_1_(ii) + t_2_(ii)), ...
                param.p2(ii).*cos(t_1_(ii) + ...
                    t_2_(ii)) - param.t.*sin(t_1_(ii) + ...
                    t_2_(ii))];
        
        
            beta = t_1_(ii) + t_2_(ii) - param.alpha;
            JC(:, :, ii) = ...
                [-param.a.*sin(t_1_(ii)) - param.b.*sin(beta), ...
                -param.b.*sin(beta); ...
                param.a*cos(t_1_(ii)) + param.b.*cos(beta), ...
                param.b.*cos(beta)];
        end
    elseif numel(t_1_) == 1 && numel(t_2_) == 1 && numel(t_3_) > 1
        %% angles are vectors with the same length
        for ii = 1:numel(t_3_)
            J1(:, :, ii) = ...
                [-param.p1.*sin(t_1_) - ...
                        param.t*cos(t_1_), 0; ...
                  param.p1.*cos(t_1_) - ...
                        param.t*sin(t_1_), 0];
        
            J2(:, :, ii) = ...
                [-param.a.*sin(t_1_) - ...
                    param.p2.*sin(t_1_ + ...
                    t_2_) - param.t.*cos(t_1_ + ...
                    t_2_), ...
                -param.p2.*sin(t_1_ + ...
                    t_2_) - param.t.*cos(t_1_ + ...
                    t_2_); ...
                param.a.*cos(t_1_) + param.p2.*cos(...
                    t_1_ + t_2_) - ...
                    param.t.*sin(t_1_ + t_2_), ...
                param.p2.*cos(t_1_ + ...
                    t_2_) - param.t.*sin(t_1_ + ...
                    t_2_)];
        
        
            beta = t_1_ + t_2_ - param.alpha;
            JC(:, :, ii) = ...
                [-param.a.*sin(t_1_) - param.b.*sin(beta), ...
                -param.b.*sin(beta); ...
                param.a*cos(t_1_) + param.b.*cos(beta), ...
                param.b.*cos(beta)];
        end
    else %% Bad
        fprintf('@getJacobians: input vectors (t1 and t2) do not have the same length.\n')
        while true == true %% Hang here
            pause(1);
        end
    end

    Jac.J1 = J1;
    Jac.J2 = J2;
    Jac.JC = JC;
end